### ISSUE TITLE
Events documentation do not match the list of events on Playground application

### ISSUE THREAD

**Issue by Narshe1412** [MicroStrategy/playground#6]
Greetings

When I open the dropdown for Events, 17 different events are listed. 

However, when you mouse over an event and click on Learn More, the linked document only explains 3 events. Would it be possible to get the documentation updated so we can know how to use the rest of the events?

Thanks

**Comment by magua-io** [comment]
@Narshe1412  Thanks for the feedback. We will try to get it updated as soon as possible and let you know once it is updated.

**Comment by xdumstr** [comment]
@Narshe1412 We released a new documentation system. This is fixed in https://microstrategy.github.io/embedding-sdk-docs/add-functionality/add-event.
